name: Context Logging

on: [pull_request]

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          echo ${{ contains( 'hello', 'll' )}}
          echo ${{ startsWith( 'hello', 'he' )}}
          echo ${{ endsWith( 'hello', 'lo' )}}
          echo ${{ format( 'hello {0} {1} {2}', 'World', '!', '!' )}}

  one:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    timeout-minutes: 360 #longest amount of time the job can take before it is cancelled
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        continue-on-error: true #will continue other steps even if this step fails
      - name: Dump job context
        if: failure() #will run even if previous step failed
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        if: always() #will always run even if previous step failed
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"